In [1]:
import torch
print(torch.__version__)

1.12.1+cu113


# [과제 1]  
- 텐서 x에서 음수값의 개수를 반환하는 함수를 구현해주세요.

In [13]:
# [과제 1]
def num_negative(x):
  """
  Return the number of negative values in the tensor x

  Inputs:
  - x: A tensor of any shape
 
  Returns:
  - num_neg: Number of negative values in x
  """

  num_neg = torch.numel(x[x<0])
  ##############################################################################
  # TODO: Use boolean masks to count the number of negative elements in x.     #
  # * 힌트 : 텐서 a[a < 0]의 길이를 재면 됩니다. 길이는 shape으로 알아낼 수 있습니다.
  ##############################################################################
  # Replace "pass" statement with your code
  pass
  ##############################################################################

  return num_neg

# [과제 1] 확인
torch.manual_seed(598)
x0 = torch.tensor([[-1, -1, 0], [0, 1, 2], [3, 4, 5]])
x1 = torch.tensor([0, 1, 2, 3])
x2 = torch.randn(100, 100) # x * y shape의 값들이 정규분포 그래프 상의 랜덤값으로 초기화 된 행렬 생성
assert num_negative(x0) == 2
assert num_negative(x1) == 0
assert num_negative(x2) == 4984
print('num_negative seems to be correct!')

num_negative seems to be correct!


# [과제 2]
- one-hot vector의 행렬을 생성하는 함수를 구현해주세요.  

    - (+ **one-hot encoding** : 단어 집합의 크기를 벡터의 차원으로 하고, 표현하고 싶은 단어의 인덱스에 1의 값을 부여하고, 다른 인덱스에는 0을 부여하는 벡터 표현 방식, 이렇게 표현된 벡터가 **one-hot vector**)  
    - 예를 들어, `[1, 4, 3, 2]` 라는 정수값을 갖는 리스트가 주어졌을때, 함수는 아래와 같은 텐서를 생성해야 합니다:

```
[[0 1 0 0 0],
 [0 0 0 0 1],
 [0 0 0 1 0],
 [0 0 1 0 0]]
```


In [27]:
# [과제 2]

# x = [4, 1, 3, 2]
def make_one_hot(x):
  """
  Construct a tensor of one-hot-vectors from a list of Python integers.

  Input:
  - x: A list of N ints

  Returns:
  - y: A tensor of shape (N, C) where C = 1 + max(x) is one more than the max
       value in x. The nth row of y is a one-hot-vector representation of x[n];
       In other words, if x[n] = c then y[n, c] = 1; all other elements of y are
       zeros.
  """
  import numpy as np
  x_np = np.array(x)
  x_ten = torch.tensor(x_np)
  import torch.nn.functional as F
  y = F.one_hot(x_ten)
  ##############################################################################
  # TODO: Complete the implementation of this function.                        #
  ##############################################################################
  # Replace "pass" statement with your code
  pass
  ##############################################################################
  #                             END OF YOUR CODE                               #
  ##############################################################################
  return y

구현한 함수가 잘 작동하는지 확인!

In [28]:
# [과제 2] 확인

def check_one_hot(x, y):
  C = y.shape[1]
  for i, n in enumerate(x):
    if n >= C: return False
    for j in range(C):
      expected = 1.0 if j == n else 0.0
      if y[i, j].item() != expected: return False
  return True
      
x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)
print('Here is y0:')
print(y0)
assert check_one_hot(x0, y0), 'y0 is wrong'

x1 = [1, 3, 5, 7, 6, 2]
y1 = make_one_hot(x1)
print('\nHere is y1:')
print(y1)
assert check_one_hot(x1, y1), 'y1 is wrong'

print('all checks pass!')

Here is y0:
tensor([[0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0]])

Here is y1:
tensor([[0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 0, 0, 0]])
all checks pass!


# [과제 3]
- 행렬의 열을 정규화하는 함수를 구현해주세요. 
    - 각 열의 평균과 표준 편차를 계산한 다음 평균을 빼고 열의 각 요소에 대한 표준 편차로 나누기!
- Example:
```
x = [[ 0,  30,  600],
     [ 1,  10,  200],
     [-1,  20,  400]]
```
    - 첫번째 열: mean 0 and std 1
    - 두번째 열: mean 20 and std 10
    - 세번째 열: mean 400 and std 200

    - 정규화 후 결과는 아래와 같이 나오게 됩니다 :
```
y = [[ 0,  1,  1],
     [ 1, -1, -1],
     [-1,  0,  0]]
```

In [92]:
# [과제 3]

def normalize_columns(x):
  """
  Normalize the columns of a matrix by subtracting the mean and dividing by the
  standard deviation.
 
  Inputs:
  - x: Tensor of shape (N, M)
  
  Returns:
  - y: Tensor of shape (N, M) which is a copy of x with normalized columns.
  """
  y = x.clone()
  m = y.mean(dim =0, keepdim=True )
  s = y.std(dim=0, keepdim=True)
  y = (y-m)/s
  # Replace "pass" statement with your code
  pass
  # * 힌트
  # 1. 각 열마다 평균을 reduction operation으로 계산하여 m으로 저장하세요. 
  #   (y.mean() 사용, dim=0, keepDim=TRUE 옵션 이용) 
  # 2. columnwise std를 reduction operation으로 계산하여 s로 저장하세요.
  #   (y.std() 사용, dim=0, keepDim=TRUE 옵션 이용) 
  # 3. y에서 m을 빼고 s를 나누세요. Broadcasting이 잘 동작하는지 고민해보세요.

  return y

구현한 함수가 잘 작동하는지 확인!

In [93]:
# [과제 3 확인]
x0 = torch.tensor([[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]])
y0 = normalize_columns(x0)
print('Here is x0:')
print(x0)
print('Here is y0:')
print(y0)
assert y0.tolist() == [[0., 1., 1.], [1., -1., -1.], [-1., 0., 0.]]
assert x0.tolist() == [[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]]

Here is x0:
tensor([[  0.,  30., 600.],
        [  1.,  10., 200.],
        [ -1.,  20., 400.]])
Here is y0:
tensor([[ 0.,  1.,  1.],
        [ 1., -1., -1.],
        [-1.,  0.,  0.]])
